version: '3'

services:
  app:
    build:
      context: .
      args:
        - NODE_ENV=production
    container_name: node-prod
    command: npm start
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always