version: '3'

services:
  app:
    build: 
      context: .
      args:
        - NODE_ENV=development
    container_name: node-dev
    command: npm run dev-start
    expose:
      - "3000"
      - "9229"
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/app
    restart: always
    